version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  web:
    image: web
    build: .
    volumes:
      - .:/app
    restart: always
    ports:
      - "5000:5000"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge
